name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libpq-dev python3-dev gcc make
      
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
      
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-json-report pytest-flask

    - name: Run Hexlet action
      uses: hexlet/project-action@release
      with:
        hexlet-id: ${{ secrets.HEXLET_ID }}
        
    - name: Run tests with coverage
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
        SECRET_KEY: "dummy_test_secret"
      run: |
        coverage run --branch -m pytest --junitxml=test-results.xml
        coverage xml
        coverage html
        
    - name: Verify coverage file
      run: |
        test -f coverage.xml && echo "Coverage file exists" || echo "Coverage file missing"
        ls -lah coverage.xml

    - name: Generate HTML coverage report
      run: |
        echo "HTML coverage report generated at htmlcov/index.html"

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/

    - name: Check coverage threshold
      run: |
        coverage report --fail-under=85

    - name: SonarCloud Scan
      if: success()
      uses: SonarSource/sonarqube-scan-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=sroonla_python-project-83
          -Dsonar.organization=sroonla
          -Dsonar.sources=page_analyzer
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.exclusions=tests/**,**/__pycache__/**
          -Dsonar.coverage.exclusions=tests/**,**/__init__.py,wsgi.py
          -Dsonar.tests=tests
          -Dsonar.test.inclusions=tests/**/*
          -Dsonar.python.xunit.reportPath=test-results.xml