name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage pytest
        uv pip install -e .
        
    - name: Run coverage
      run: |
        mkdir -p tests
        cat > tests/test_coverage.py << EOF
        def test_app_import():
            from page_analyzer.app import app
            assert app is not None
            
        def test_db_import():
            from page_analyzer.db import get_connection
            conn = get_connection()
            assert conn is not None
            conn.close()
        EOF
        
        coverage run --source=page_analyzer -m pytest tests/test_coverage.py
        coverage xml
        
        echo "Generated files:"
        ls -la
        echo "Coverage XML content:"
        head coverage.xml
        
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: ${{ github.workspace }}